### ISSUE TITLE
[Request for Info] Visual ID

### ISSUE THREAD

**Issue by Road-block** [verkkila/AppearanceCollectionTooltip#1]
Question:
When the tooltip says "Collected" does it check that the appearance is collected from *any source* or this particular exact item source?

Also, could the red "not collected" addition be changed to "not collectible by \<class\>"
I've had guildies (who I suggested the addon to) get confused by the 2 additions with same verbiage and just different color.

I'm not much of a transmog collector but if I understand correctly there's 4 distinct statuses as it pertains to an item?
- Appearance collected from this exact item
- Appearance collected from a same model item (but not this exact one)
- Appearance not collected but collectible on this character
- Appearance not collected and not collectible on this character

Is that correct and could we get tooltip additions that match those statuses :)

**Comment by Road-block** [comment]
Talking this over with some of my guildies to make sure I understand the problem.

Most everyone is telling me that the **primary** information they're looking from the addon is number (2) on the list above.
This __appearance__ is collected (from this exact item or not does not matter)

Exact source might be interesting to hardcore collectors but not really helpful could be a postfix / addendum on the tooltip but not really important.

So the suggested tooltip additions would be
- "Collected" -- The visualID / Appearance, not exact source, exact source can be an optional indicator
- "Not Collected" -- But collectible on this character
- [Not Collected is implied] "Not Collectible on \<Current Class\>"

Description should clearly distinguish between statuses in addition to color code (if for nothing else, lots of folks with colorblindness)

**Comment by verkkila** [comment]
The purpose is to indeed check for status 2, i.e. whether the appearance that this item uses is in the player's collection.

Like you mentioned it is the information I assume majority of transmog collectors are interested in but checking for the exact item could be an optional toggle in the future.

I do like the idea of not relying on color-coding for the collection status, like you said it limits accessibility (TransmogOutfitManager has the same situation with the current border assets).

I'll change the tooltip texts in the next version to something along the lines of:
- <Green> Collected
- <Yellow> Collectable
- <Red> Not collectable on %condition%

With %condition% most likely being the player character's class, but I'll have to check if there are niche cases, for example what happens if an Alliance player views items from the Horde T9 set.

Thanks for the suggestion!

**Comment by Road-block** [comment]
Sorry my guldie initially approached me about this as a problem in the sense that the addon shows completed only for the exact source and not the appearance. 
I'll ask them to forward me some screenshots to verify that's the case.

To make sure you are saying that the addon currently / already shows a "completed" status based on visual id - appearance and not exact source.

**Comment by verkkila** [comment]
I was mistaken, the tooltip item's appearance was incorrectly being checked against the appearance source rather than the "general" model / appearance of the item. I've fixed this in 1.0.3 as well as added more verbosity to the tooltips. Good find and thanks for bringing this up.

If there was something I missed from your comments please let me know.
